image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

stages:
  - prepare
  - test
  - build

install-dependencies:
  stage: prepare
  script:
  - npm update @angular/cli
  - npm update puppeteer
  - npm update

perform-tests:
  stage: test
  script:
    - node_modules/.bin/ng test
  only:
    - master

build:
  stage: build
  script: 
    - node_modules/.bin/ng build --env=prod