image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

stages:
  - prepare
  - test
  - build

install-angular-cli:
  stage: prepare
  script:
    - npm update -g @angular/cli
    
install-angular-dependencies:
  stage: prepare
  script:
  - npm update

perform-tests:
  stage: test
  script:
    - ng test
  only:
    - master

build:
  stage: build
  dependencies: 
    - install
  script: 
    - ng build --env=prod